# Generated by Django 4.1.4 on 2022-12-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Likes'),
        ),
    ]
